server:
  port: 8001
spring:
  application:
    name: demo1
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pengzhaojun/spring-cloud.git
          search-paths: config-repo
